/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/bridge.glb");
  return (
    <group {...props} dispose={null} position={[0, 0, -2.5]} scale={0.7}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stairs.geometry}
        material={materials.Base_Material}
        position={[3.51, 0, 0.01]}
        rotation={[Math.PI / 2, 0, -1.57]}
        scale={[0.9, 0.39, 0.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stairs001.geometry}
        material={materials.Base_Material}
        position={[-2.73, 0, 0.01]}
        rotation={[Math.PI / 2, 0, 1.58]}
        scale={[0.9, 0.39, 0.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bridge01.geometry}
        material={materials["Stone.034"]}
        position={[0.33, 1.73, -0.02]}
        scale={[0.99, 0.84, 1.1]}
      />
    </group>
  );
}

useGLTF.preload("/bridge.glb");
