/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, 

 } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function Helicopter({...props}) {
    const group = useRef()
    const { nodes, materials } = useGLTF('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/helicopter/model.gltf')
    const helicopter = useRef()
    useFrame((state, delta) => {
        const time = state.clock.getElapsedTime()
        const y = Math.sin(time + 2) * .005
        const x = Math.cos(time + 5) * .005
        group.current.position.y += y
        group.current.position.x += x
    })

    return (
            <group ref={group} dispose={null} {...props} >
                <mesh geometry={nodes.BackWingsContainer.geometry} material={nodes.BackWingsContainer.material} position={[-0.2, 1.14, -3.1,]} />
                <mesh geometry={nodes.EngineStrut.geometry} material={nodes.EngineStrut.material} position={[0.29, 3.06, -0.35,]} />
                <mesh geometry={nodes.GlassGasket.geometry} material={materials.WindsheildGasket} position={[0.39, 1.08, 0.2,]} />
                <mesh geometry={nodes.GlassGasketTwo.geometry} material={materials['WindsheildGasket.001']} position={[0.44, 1.09, 0.51,]} />
                <mesh geometry={nodes.BackMotor.geometry} material={nodes.BackMotor.material} position={[-0.14, 1.14, -3.11,]} />
                <mesh geometry={nodes.HelicopterBackWings.geometry} material={nodes.HelicopterBackWings.material} position={[-0.23, 1.14, -3.09,]} />
                <mesh geometry={nodes.HelicopterBody001.geometry} material={nodes.HelicopterBody001.material} position={[1110.33, 0.72, -196.12,]} />
                <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.22, 1.51, -3.17,]} />
                <group position={[0.44, 1.08, 0.48,]} >
                <mesh geometry={nodes.Sphere007.geometry} material={materials.Windsheild} />
                <mesh geometry={nodes.Sphere007_1.geometry} material={materials.WindSheildDark} />
                </group>
                <mesh geometry={nodes.TopEngine.geometry} material={nodes.TopEngine.material} position={[0.25, 1.73, -0.56,]} />
                <mesh geometry={nodes.StandPlane.geometry} material={materials.Stand} position={[-2183.61, 0.37, 385.46,]} />
                <group position={[0.24, 1.09, -0.64,]} >
                <mesh geometry={nodes.Sphere010.geometry} material={materials['HelicopterBody.001']} />
                <mesh geometry={nodes.Sphere010_1.geometry} material={materials.Interior} />
                </group>
                <mesh geometry={nodes.GatlingGun.geometry} material={nodes.GatlingGun.material} position={[-17127.32, 0.58, 3020.13,]} />
                <mesh geometry={nodes.TopFin.geometry} material={nodes.TopFin.material} position={[0.29, 2.34, -0.35,]} rotation={[Math.PI, -0.53, Math.PI,]} />

            </group>
    )
}

useGLTF.preload('https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/helicopter/model.gltf')